name: Unit tests

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake .
    - name: build
      run: make
    - name: test
      run: ctest
